# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c65667d982b2be9a95fc346f821b4cd09ba0e9c4fbd06b3afc28c45b04777984f3cbf2faaaac3461296c6b38f89ca459c682a0bdd46d983589eb335106c54ae

test:
  secret_key_base: 37a85706c5267fedebf463139db2c6c3677e1ceba5ce08847eeeb8e3fa5e2b44e0d92208c8e4b8e6b7d1fb8e312bcd8405b678bbae5c43d1af47d0ab342feb90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
